name: Action Workflow

on: 
  push:
    branches: 
      - main
      - demo/*
      - '!sample'
      
    tags:
      - vi.*
    
    paths: 
      - '**.js'
      - '**.md'
      - 'docs/*'
      - '!docs/file.txt'

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSHOP
          echo "${{ github.token }}"

      - name: checkout
        uses: actions/checkout@v1

      - name: List Files After Checkout
        run: |
          pwd
          ls

      - name: Simple Javascript Action
        id: hello
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: 'devopshint'

      - name: Get the output time
        run: echo "${{ steps.hello.outputs.time }}"
