name: Action Workflow

on: [push]
 
jobs:
    run-github-actions:
        runs-on: ubuntu-latest
        steps:
          - name: List files
            run:
              pwd
              ls
          - name: Simple Javascript Action
            id: hello
            uses: actions/helo-world-javascript-action@v1
            with: 
              who-to-great: devopshint
      
          - name: Get the output time
            run: echo "${{ steps.hello.outputs.time }}"
                
      
