name: Action Workflow

on: 
  schedule: 
    - cron: "1 * * * *"
  
  pull_request:
    types: [closed, assigned, opened, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE

      - name: Checkout
        uses: actions/checkout@v2

      - name: List Files After Checkout
        run: |
          pwd
          ls -a
